package menus;


import boards.CreateBoard;
import java.awt.Color;
import java.io.*;
import java.net.*;
import java.net.ServerSocket;
import java.net.UnknownHostException;
import java.util.Locale;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import questions.All;
import static reader.FilesReader.FilesReader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author domin
 */
public class CreateMenu extends javax.swing.JFrame {
    
    final Pattern regIP= Pattern.compile("\\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3}");
    String myIP;
    int boardSize = 5;
    String file;
    ServerSocket ss;
    Socket sk;
    int port;
    All questions;
    final String fileList = "files.txt";
    /**
     * Creates new form CreateMenu
     */
    
    public CreateMenu() throws UnknownHostException {
        initComponents();
        this.setTitle("Quiz Tac Toe");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        btn5x5.setSelected(true);
        myIP = ""+InetAddress.getLocalHost();
        labelMyIP.setText(myIP.substring(myIP.indexOf("/")+1, myIP.length()));
        chooseFile.removeAllItems();
        try(Scanner s = new Scanner(new FileInputStream(fileList)).useLocale(Locale.US)){
            while(s.hasNextLine()){
                chooseFile.insertItemAt(s.nextLine(),chooseFile.getItemCount());
            }
            chooseFile.setSelectedIndex(0);
        } catch (FileNotFoundException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelMyIP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn9x9 = new javax.swing.JRadioButton();
        btn7x7 = new javax.swing.JRadioButton();
        btn5x5 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        TFQuestions = new javax.swing.JTextField();
        lBadFile = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        chooseFile = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        chooseMyC = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        chooseEnemyC = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TFport = new javax.swing.JTextField();
        lBadPort = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quiz Tac Toe");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Board size:");

        labelMyIP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Your IP:");

        buttonGroup1.add(btn9x9);
        btn9x9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn9x9.setText("9x9");
        btn9x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9x9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn7x7);
        btn7x7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn7x7.setText("7x7");
        btn7x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7x7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn5x5);
        btn5x5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn5x5.setText("5x5");
        btn5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5x5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Questions file:");

        TFQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFQuestionsActionPerformed(evt);
            }
        });

        lBadFile.setForeground(new java.awt.Color(102, 102, 102));
        lBadFile.setText("for example: questions or questions.txt");

        btnPlay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        chooseFile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Enemy Color:");

        chooseMyC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "green", "yellow", "blue", "red", "cyan", "magenta", "orange" }));
        chooseMyC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseMyCActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Your Color:");

        chooseEnemyC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "green", "yellow", "blue", "red", "cyan", "magenta", "orange" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Port:");

        TFport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFportKeyTyped(evt);
            }
        });

        lBadPort.setForeground(new java.awt.Color(102, 102, 102));
        lBadPort.setText("number 0 - 65535");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMyIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseFile, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFport)
                                    .addComponent(lBadFile, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn7x7)
                                    .addComponent(btn5x5)
                                    .addComponent(btn9x9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseMyC, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseEnemyC, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lBadPort, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMyIP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5x5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn7x7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn9x9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lBadFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lBadPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseMyC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseEnemyC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay)
                    .addComponent(btnBack))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7x7ActionPerformed
        boardSize = 7;
    }//GEN-LAST:event_btn7x7ActionPerformed

    private void btn5x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5x5ActionPerformed
        boardSize = 5;
    }//GEN-LAST:event_btn5x5ActionPerformed

    private void TFQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFQuestionsActionPerformed
        
    }//GEN-LAST:event_TFQuestionsActionPerformed

    private void btn9x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9x9ActionPerformed
        boardSize = 9;
    }//GEN-LAST:event_btn9x9ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        //getting file
        file = TFQuestions.getText().strip();
        if(file.equals("")){
            file = String.valueOf(chooseFile.getSelectedItem());
        }
        
        //if it hasnt got .txt
        if(file.length()<4 || !file.substring(file.length()-4).equals(".txt")){
            file = file + ".txt";
        }
        
        
        if(TFport.getText().isBlank()){
            lBadPort.setText("input number");
            lBadPort.setForeground(Color.red);
            return;
        }
        port = Integer.parseInt(TFport.getText());
        if(port >65535){
            lBadPort.setText("bad number");
            lBadPort.setForeground(Color.red);
            return;
        }
        
        
        if(chooseMyC.getSelectedIndex() == chooseEnemyC.getSelectedIndex()){
            lBadPort.setText("colors are same");
            lBadPort.setForeground(Color.red);
            return;
        }
        
        
        try (Scanner s = new Scanner(new FileInputStream(file)).useLocale(Locale.US)){
            questions = FilesReader(s);
            if(questions == null){
                lBadFile.setForeground(Color.red);
                lBadFile.setText("bad file");
                return;
            }
            jLabel1.setText("Connecting...");
            ss = new ServerSocket(port);
            sk = ss.accept();
            CreateBoard window = new CreateBoard(sk,boardSize,questions, String.valueOf(chooseMyC.getSelectedItem()), String.valueOf(chooseEnemyC.getSelectedItem()));
            window.setVisible(true);
            dispose();
        } catch (FileNotFoundException ex) {
            lBadFile.setForeground(Color.red);
            lBadFile.setText("bad file");
        }catch(BindException ex){
            lBadPort.setForeground(Color.red);
            lBadPort.setText("port is already in use");
        } catch (IOException ex) {
            showMessageDialog(null, ex, "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainMenu window = new MainMenu();
        window.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void chooseMyCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseMyCActionPerformed
        
    }//GEN-LAST:event_chooseMyCActionPerformed

    private void TFportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFportKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_TFportKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CreateMenu().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(CreateMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFQuestions;
    private javax.swing.JTextField TFport;
    private javax.swing.JRadioButton btn5x5;
    private javax.swing.JRadioButton btn7x7;
    private javax.swing.JRadioButton btn9x9;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> chooseEnemyC;
    private javax.swing.JComboBox<String> chooseFile;
    private javax.swing.JComboBox<String> chooseMyC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lBadFile;
    private javax.swing.JLabel lBadPort;
    private javax.swing.JLabel labelMyIP;
    // End of variables declaration//GEN-END:variables
}
